INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Monitor', 'Electrónica', 2000, 15);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Cuerda para saltar', 'Deportes', 40, 50);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Taza', 'Hogar', 35, 80);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Auriculares', 'Electrónica', 250, 35);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Sarten', 'Hogar', 200, 30);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Resaltador', 'Papeleria', 6, 130);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Pelota de fútbol', 'Deportes', 300, 20);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Manzana', 'Alimentos', 10, 300);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Teclado', 'Electrónica', 300, 25);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Leche', 'Alimentos', 20, 200);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Yogurt', 'Alimentos', 25, 180);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Pesas', 'Deportes', 150, 10);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Cuchillo', 'Hogar', 25, 120);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Cargador USB', 'Electrónica', 120, 50);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Plato', 'Hogar', 50, 70);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Pan', 'Alimentos', 15, 250);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Cable HDMI', 'Electrónica', 90, 60);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Sacapuntas', 'Papeleria', 4, 180);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Raqueta de tenis', 'Deportes', 500, 15);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Cereal', 'Alimentos', 50, 120);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Botella deportiva', 'Deportes', 50, 100);
INSERT INTO articulos (nombre, categoria, precio, cantidad) VALUES ('Cubiertos', 'Hogar', 80, 60);

